config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "user/omniauth_callbacks"}
  root "products#index"


  resources :users, only: :show
  resources :products, only: [:show, :index] do
    resources :comments
  end

  namespace :admin do
    root "admin/products#index"
    resources :products, except: [:show]
    resources :categories
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.role == "admin"
      can :manage, :all
    else user.role == "member"
      can :read, Order
      can :create, Order
      can :update, Order
    end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  mount_uploader :image, ImageUploader

  validates :title_name, uniqueness: true, presence: true, length: {maximum: 100}
  validates :description, length: {maximum: 200}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, presence: true, length: {maximum: 200}
  scope :newest, -> {order(created_at: :desc)}

  delegate :fullname, to: :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :comments
  has_many :order_details

  validates :name, presence: true, uniqueness:true, length: {maximum: 50}
  validates :quantity, numericality: true, allow_nil: true
  validates :price, numericality: true, allow_blank: true
  validates :category_id, presence: true

  ratyrate_rateable "quality"
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user

  validates :title_name, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests
  has_many :comments
  has_many :orders

  validates :fullname, presence: true, length: {maximum: 50}
  validates :phone_number, numericality: true, allow_blank: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  enum role: [:admin, :member, :guest]

  ratyrate_rater
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :load_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.page params[:page]
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "update successfully"
      redirect_to admin_categories_path
    else
      flash[:success] = "update fail !"
      render :edit
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "create successfully"
      redirect_to admin_categories_path
    else
      flash[:danger] = "create failed!"
      render :new
    end
  end

  def destroy
    if @category.products.any?
      flash[:danger] = "you must delete products first!"
    elsif @category.destroy
      flash[:success] = "delete successfully!"
    else
      flash[:success] = "update fail !"
    end
    redirect_to :back
  end

  private
  def category_params
    params.require(:category).permit :title_name, :description, :image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :load_categories

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def check_user
    if user_signed_in? && current_user.role == "admin"
      redirect_to admin_products_path
    end
  end

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end

  def load_categories
    @categories = Category.all
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :address, :phone_number
    end
    devise_parameter_sanitizer.permit :account_update do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :current_password, :address, :phone_number
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      flash[:success] = "Comment was created"
    else
      flash[:danger] = "Comment errors"
    end
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit :content,
      :user_id, :product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show, :edit]
  before_action :check_user, only: :index

 def index
    if params[:category_id_eq].present?
      param = Hash.new
      param[:category_id_eq] = params[:category_id_eq]
      @q = Product.ransack param
    else
      @q = Product.ransack params[:q]
    end
    @products = (@q.result.order created_at: :desc).page(params[:page])
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def show
    @categories = Category.all
    @comment = Comment.new product: @product
    @comments = @product.comments.newest.page(params[:page])
      .paginate page: params[:page], per_page: Settings.comment.per_page
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find_by id: params[:id]
      if obj.nil?
        render :json => false
      else
        obj.rate params[:score].to_f, current_user, params[:dimension]
        render :json => true
      end
    else
      render :json => false
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def show
      if valid_page?
        render template: "static_pages/#{params[:page]}"
      else
        render file: "public/404.html", status: :not_found
      end
    end

    private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"))
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: :show

  def show
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title page_title = ""
    base_title = t "framgia_food_and_drinks"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_category.html.erb
<% @categories.each_with_index do |category, index| %>
  <tr class=" <%= (index + 1).even? ? "success": "danger" %>">
    <td class="course-name">
      <%= category.title_name %>
    </td>
    <td class="course-name">
      <%= category.description %>
    </td>
    <td>
      <%= link_to edit_admin_category_path(category),
        class: "btn btn-default btn-xs" do %>
        <span class="glyphicon glyphicon-edit"></span>
          <%= "Edit" %>
      <% end %>
      <%= link_to admin_category_path(category), method: :delete,
        class: "btn btn-danger btn-xs", data: {confirm:
        "Are you sure ???"} do %>
        <span class="glyphicon glyphicon-remove"></span>
          <%= "Delete" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :title_name, class: "form-control", required: "true" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Cancel", admin_categories_path, class: "btn btn-default" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, "Edit Category" %>
<div class="row">
  <h1 class="fixed-h1"><%= "Edit Category" %></h1>
  <div class="col-md-6 col-md-offset-4">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide title: "Index categories" %>
<%= link_to "Add new", new_admin_category_path,
  {class: "btn btn-primary"} %>
<% if @categories.any? %>
  <table class="table table-hover">
    <tr>
      <th><%= "Category name" %></th>
      <th><%= "Description" %></th>
      <th></th>
    </tr>
    <%= render "category" %>
  </table>
  <div class="text-center">
    <%= paginate @categories %>
  </div>
<% end %>

app/views/admin/categories/new.html.erb
<% provide title: "Add Category" %>
<% provide :button_text, "Create" %>
<h1 class="fixed-h1"><%= "Add Category" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <%= render "form" %>
  </div>
</div>