config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "user/omniauth_callbacks"}
  root "products#index"


  resources :users, only: :show
  resources :products, only: [:show, :index] do
    resources :comments
  end

  namespace :admin do
    root "admin/products#index"
    resources :products, except: [:show]
    resources :categories
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.role == "admin"
      can :manage, :all
    else user.role == "member"
      can :read, Order
      can :create, Order
      can :update, Order
    end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  mount_uploader :image, ImageUploader

  validates :title_name, uniqueness: true, presence: true, length: {maximum: 100}
  validates :description, length: {maximum: 200}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, presence: true, length: {maximum: 200}
  scope :newest, -> {order(created_at: :desc)}

  delegate :fullname, to: :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :comments
  has_many :order_details

  validates :name, presence: true, uniqueness:true, length: {maximum: 50}
  validates :quantity, numericality: true, allow_nil: true
  validates :price, numericality: true, allow_blank: true
  validates :category_id, presence: true

  ratyrate_rateable "quality"
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user

  validates :title_name, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests
  has_many :comments
  has_many :orders

  validates :fullname, presence: true, length: {maximum: 50}
  validates :phone_number, numericality: true, allow_blank: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  enum role: [:admin, :member, :guest]

  ratyrate_rater
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :load_product, except: [:show, :new, :create, :index]

  def index
    if params[:category_id_eq].present?
      param = Hash.new
      param[:category_id_eq] = params[:category_id_eq]
      @q = Product.ransack param
    else
      @q = Product.ransack params[:q]
    end
    @products = (@q.result.order created_at: :desc).page(params[:page])
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "admin_control.product.update_success"
      redirect_to admin_products_path
    else
      flash[:danger] = t "admin_control.product.update_fail"
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "delete successfully!"
    else
      flash[:success] = "update fail !"
    end
    redirect_to :back
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "create successfully"
      redirect_to admin_products_path
    else
      flash[:danger] = "create failed!"
      render :new
    end
  end


  private
  def product_params
    params.require(:product).permit :name, :price, :image, :description,
      :quantity, :category_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :load_categories

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def check_user
    if user_signed_in? && current_user.role == "admin"
      redirect_to admin_products_path
    end
  end

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end

  def load_categories
    @categories = Category.all
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :address, :phone_number
    end
    devise_parameter_sanitizer.permit :account_update do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :current_password, :address, :phone_number
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      flash[:success] = "Comment was created"
    else
      flash[:danger] = "Comment errors"
    end
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit :content,
      :user_id, :product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show, :edit]
  before_action :check_user, only: :index

 def index
    if params[:category_id_eq].present?
      param = Hash.new
      param[:category_id_eq] = params[:category_id_eq]
      @q = Product.ransack param
    else
      @q = Product.ransack params[:q]
    end
    @products = (@q.result.order created_at: :desc).page(params[:page])
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def show
    @categories = Category.all
    @comment = Comment.new product: @product
    @comments = @product.comments.newest.page(params[:page])
      .paginate page: params[:page], per_page: Settings.comment.per_page
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find_by id: params[:id]
      if obj.nil?
        render :json => false
      else
        obj.rate params[:score].to_f, current_user, params[:dimension]
        render :json => true
      end
    else
      render :json => false
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def show
      if valid_page?
        render template: "static_pages/#{params[:page]}"
      else
        render file: "public/404.html", status: :not_found
      end
    end

    private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"))
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: :show

  def show
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title page_title = ""
    base_title = t "framgia_food_and_drinks"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/edit.html.erb
<% provide :title, t(".edit_product_title") %>
<h1 class="fixed-h1"><%= t ".edit_product" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, @categories.collect{|p| [p.title_name, p.id]},
          {include_blank: false}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
      </div>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
      <%= link_to t(".cancel"), admin_products_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="portlet box lst-product">
  <div class="portlet-title">
    <div class="caption">
      <span class="caption-title">
      </span>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="search-container">
      <%= search_form_for [:admin, @q] do |f| %>
        <div class="field">
          <div class="col-md-3 no-padding-right">
            <%= f.text_field :name_cont, class: "form-control",
              placeholder: t(".search_by_name") %>
          </div>
          <div class="col-sm-3">
            <%= f.collection_select :category_id_eq, @categories, :id,
              :title_name, {include_blank: t("all")}, class: "form-control" %>
          </div>
          <%= submit_tag (t".bnt_search"),
            class: "btn btn-default btn-search-top clear" %>
          <%= link_to "New Product", new_admin_product_path,
            {class: "btn btn-primary"} %>
        </div>
        </div>
      <% end %>
    </div>
    <div class="data-container">
      <div class="list-products row ls-products">
        <% @products.each do |product| %>
          <div class="col-item col-md-3 col-sm-4 col-xs-2 pro-item">
            <div class="item" >
              <div class="img-product">
                <%= link_to product_path product.id do %>
                  <%= image_tag product.image.url.nil? ? "no_image.png" : product
                  .image %>
                <% end %>
              </div>
              <div class="detail-product">
                <h4>
                  <%= link_to product_path product.id do %>
                    <%= product.name %>
                  <% end %>
                </h4>
                <p class="price text-danger">
                  <%= t ".price"%>
                  <%= product.price.nil? ? t(".not_found") : "#{product.price} $" %>
                </p>
                <p class="add-cart">
                  <%= link_to t(".edit"), edit_admin_product_path(product) %>
                  <%= link_to admin_product_path(product), method: :delete,
                    class: "btn btn-danger btn-xs", data: {confirm:
                    "Are you sure ???"} do %>
                    <span class="glyphicon glyphicon-remove"></span>
                      <%= "Delete" %>
                  <% end %>
                <p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row wrap-paging">
        <div class="col-sm-12 text-center">
          <%= paginate @products, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, "New Product" %>
<h1 class="fixed-h1"><%= "New Product" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, @categories.collect{|p| [p.title_name, p.id]},
          {include_blank: false}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
      </div>

      <%= f.submit "Create", class: "btn btn-primary" %>
      <%= link_to "Cancel", admin_products_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
  <div class="comment_item">
    <span class="text-primary"> <%= comment.content %> </span>
    <%= comment.fullname %>,
    <%= time_ago_in_words comment.created_at %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@product, @comment] do |f| %>
      <%= f.hidden_field :product_id, value: @product.id %>
      <%= f.text_area :content, class: "form-control required",
        required: "true" %>
      <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="portlet box lst-product">
  <div class="portlet-title">
    <div class="caption">
      <span class="caption-title">
      </span>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="search-container">
      <%= search_form_for @q do |f| %>
        <div class="field">
          <div class="col-md-3 no-padding-right">
            <%= f.text_field :name_cont, class: "form-control",
              placeholder: t(".search_by_name") %>
          </div>
          <div class="col-sm-3">
            <%= f.collection_select :category_id_eq, @categories, :id,
              :title_name, {include_blank: t("all")}, class: "form-control" %>
          </div>
          <%= submit_tag (t".bnt_search"),
            class: "btn btn-default btn-search-top clear" %>
        </div>
        </div>
      <% end %>
    </div>
    <div class="data-container">
      <div class="list-products row ls-products">
        <% @products.each do |product| %>
          <div class="col-item col-md-3 col-sm-4 col-xs-2 pro-item">
            <div class="item" >
              <div class="img-product">
                <%= link_to product_path product.id do %>
                  <%= image_tag product.image.url.nil? ? "no_image.png" : product
                  .image %>
                <% end %>
              </div>
              <div class="detail-product">
                <h4>
                  <%= link_to product_path product.id do %>
                    <%= product.name %>
                  <% end %>
                </h4>
                <p class="price text-danger">
                  <%= t ".price"%>
                  <%= product.price.nil? ? t(".not_found") : "#{product.price} $" %>
                </p>
                <p class="add-cart">
                  <%= link_to t(".choose"), "javascript:;",
                    class: "btn btn-success btn-add-cart", data: {id: product.id,
                    url: "#"} %>
                <p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row wrap-paging">
        <div class="col-sm-12 text-center">
          <%= paginate @products, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% provide :title, t(".page_title") %>
<div>
  <div class="row">
    <div class="col-md-3 left">
      <%= image_tag @product.image.url.nil? ?
        "no_image.png" : @product.image %>
    </div>
    <div class="col-md-3">
      <div class="product-price">
        <span class="badge"><%= t "Price" %>:</span>
          <a class="text-danger">
            <%= @product.price.nil? ? t(".not_found") : "#{@product.price} $" %>
          </a>
          <br>
      </div>
      <div class="product-name">
        <p>
        <span class="label label-success"><%= t".product_name" %></span><span><%= @product.name %></p>
      </div>
      <div class="product-description">
        <p>
          <span class="label label-success"><%= t".product_description" %></span>
          <span><%= @product.description %></span>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1 col-md-offset-2 size-text">
      <%= link_to t(".back"), root_path %>
    </div>
    <div class="col-md-2">
      <%= rating_for @product, "quality", star: 5, disable_after_rate: false,
        enable_half: true %>
    </div>
    <div class="col md-2 size-text">
      <span class="label label-info"> <%= t".rate_avg" %>:
        <%= unless @product.average("quality").nil?
          (@product.average("quality").avg.round Settings.rating.per_avg)
        end %>
      </span>
    </div>
  </div>
</div>
<br><br><br>
<div class="title-show">
  <%=  t(".users_comment") %><%= @comments.size %>
</div>
<div class="main-show-comment box_width_common">
  <%= render "comments/comment" %>
  <%= paginate @comments %>
  <div>
    <% unless current_user.nil? %>
      <%= render "comments/form" %>
    <% end %>
  </div>
</div>