config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "user/omniauth_callbacks"}
  root "products#index"


  resources :users, only: :show
  resources :products, only: [:show, :index] do
    resources :comments
  end

  namespace :admin do
    root "admin/products#index"
    resources :products, except: [:show]
    resources :categories
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.role == "admin"
      can :manage, :all
    else user.role == "member"
      can :read, Order
      can :create, Order
      can :update, Order
    end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  mount_uploader :image, ImageUploader

  validates :title_name, uniqueness: true, presence: true, length: {maximum: 100}
  validates :description, length: {maximum: 200}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, presence: true, length: {maximum: 200}
  scope :newest, -> {order(created_at: :desc)}

  delegate :fullname, to: :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :comments
  has_many :order_details

  validates :name, presence: true, uniqueness:true, length: {maximum: 50}
  validates :quantity, numericality: true, allow_nil: true
  validates :price, numericality: true, allow_blank: true
  validates :category_id, presence: true

  ratyrate_rateable "quality"
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user

  validates :title_name, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests
  has_many :comments
  has_many :orders

  validates :fullname, presence: true, length: {maximum: 50}
  validates :phone_number, numericality: true, allow_blank: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  enum role: [:admin, :member, :guest]

  ratyrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :load_categories

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def check_user
    if user_signed_in? && current_user.role == "admin"
      redirect_to admin_products_path
    end
  end

  def load_product
    @product = Product.find_by id: params[:id]
    if @product.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end

  def load_categories
    @categories = Category.all
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :address, :phone_number
    end
    devise_parameter_sanitizer.permit :account_update do |user_params|
      user_params.permit :fullname, :email, :password,
      :password_confirmation, :current_password, :address, :phone_number
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      flash[:success] = "Comment was created"
    else
      flash[:danger] = "Comment errors"
    end
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit :content,
      :user_id, :product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show, :edit]
  before_action :check_user, only: :index

 def index
    if params[:category_id_eq].present?
      param = Hash.new
      param[:category_id_eq] = params[:category_id_eq]
      @q = Product.ransack param
    else
      @q = Product.ransack params[:q]
    end
    @products = (@q.result.order created_at: :desc).page(params[:page])
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def show
    @categories = Category.all
    @comment = Comment.new product: @product
    @comments = @product.comments.newest.page(params[:page])
      .paginate page: params[:page], per_page: Settings.comment.per_page
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find_by id: params[:id]
      if obj.nil?
        render :json => false
      else
        obj.rate params[:score].to_f, current_user, params[:dimension]
        render :json => true
      end
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: :show

  def show
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title page_title = ""
    base_title = t "framgia_food_and_drinks"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_header.html.erb
<div id="top" class="fixed">
  <div class="wrapper clearfix">
    <nav class="top-bar-section clearfix">
      <ul class="left clearfix">
        <li class="show-mobile">
          <a href="#sidebar" class="icon i-mobile-menu"> </a>
        </li>
        <%= link_to (t "framgia_food_and_drinks"), "#", id: "logo" %>
        <li class="item01 home hide-mobile">
          <a href="<%= admin_products_path %>" class="">
            <i></i>
          </a>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= "Manage" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Products", admin_products_path %></li>
              <li><%= link_to "Categories", admin_categories_path %></li>
              <li><%= link_to "Order", "#" %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to (t ".login"),  new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t(".about"), "about" %></li>
      <li>|</li>
      <li><%= link_to t(".news"), "news" %></li>
    </ul>
  </nav>
  <div class="footer-above">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= t".copyright" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="top" class="fixed">
  <div class="wrapper clearfix">
    <nav class="top-bar-section clearfix">
      <ul class="left clearfix">
        <li class="show-mobile">
          <a href="#sidebar" class="icon i-mobile-menu"> </a>
        </li>
        <%= link_to (t "framgia_food_and_drinks"), root_path, id: "logo" %>
        <li class="item01 home hide-mobile">
          <a href="<%= products_path %>" class="">
            <i></i>
          </a>
        </li>
        <li class="item02 has-sub hide-mobile">
          <a href="#">
            Menu
            <span class="arr"></span>
          </a>
          <div id="hidden-sub">
            <div class="wrapper">
              <ul class="sub-nav">
                <% @categories.each do |category| %>
                  <li>
                    <a href="<%= products_path(@product, category_id_eq: category.id) %>">
                      <span class="thumb">
                        <%= image_tag category.image.url.nil? ? "no_image.png" : category
                  .image %>
                      </span>
                      <span class="shadow">
                        <%= image_tag "s01.png", alt: "s01" %>
                      </span>
                      <span class="text"><%= category.title_name %></span>
                    </a>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </li>
        <li class="item03 hide-mobile">
          <a href="#">
            <%= t ".order" %>
          </a>
        </li>
        <li class="item04 hide-mobile">
          <a href="#">
            <%= t ".promotion" %>
          </a>
        </li>
        <li class="item05 hide-mobile">
          <a href="#">
            <%= t ".store" %>
          </a>
        </li>
        <li class="item05 hide-mobile">
          <a href="#">
            <%= t ".franchising" %>
          </a>
        </li>
        <li class="item07 cart">
          <a href="#" class="">
            <i></i>
            <span class="cartNumber">0</span>
          </a>
        </li>
        <% if user_signed_in? %>
          <% if current_user.role == "admin" %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= "Manage" %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Products", admin_products_path %></li>
                <li><%= link_to "Categories", admin_categories_path %></li>
                <li><%= link_to "Order", "#" %></li>
              </ul>
            </li>
          <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t".account" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".profile"), current_user %></li>
            <li><%= link_to t(".settings"), edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to (t ".login"),  new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_header2.html.erb
<div id="top">
  <div class="wrapper clearfix">
    <nav class="top-bar-section clearfix">
      <ul class="left clearfix">
        <li class="show-mobile">
          <a href="#sidebar" class="icon i-mobile-menu"> </a>
        </li>
        <%= link_to (t "framgia_food_and_drinks"), root_path, id: "logo" %>
        <li class="item01 home hide-mobile">
          <a href="../products" class="">
            <i></i>
          </a>
        </li>
        <li class="item02 has-sub hide-mobile">
          <a href="#">
            Menu
            <span class="arr"></span>
          </a>
          <div id="hidden-sub">
            <div class="wrapper">
              <ul class="sub-nav">
                <% @categories.each do |category| %>
                  <li>
                    <a href="<%= products_path(@product, query: category.id) %>">
                      <span class="thumb">
                        <%= image_tag "no_image.png", alt: "ill1" %>
                      </span>
                      <span class="shadow">
                        <%= image_tag "s01.png", alt: "s01" %>
                      </span>
                      <span class="text"><%= category.title_name %></span>
                    </a>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </li>
        <li class="item03 hide-mobile">
          <a href="#">
            Order
          </a>
        </li>
        <li class="item04 hide-mobile">
          <a href="#">
            Promotion
          </a>
        </li>
        <li class="item05 hide-mobile">
          <a href="#">
            Store
          </a>
        </li>
        <li class="item05 hide-mobile">
          <a href="#">
            Franchising
          </a>
        </li>
        <li class="item07 cart">
          <a href="#" class="">
            <i></i>
            <span class="cartNumber">0</span>
          </a>
        </li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t".account" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t(".profile"), current_user %></li>
            <li><%= link_to t(".settings"), edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to (t ".login"),  new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/applicaiton.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BaseApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BaseApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <% if user_signed_in? && current_user.role == "admin" %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>
    <div class="container" style="margin-top: 80px">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>